Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -131,3 +131,14 @@ jobs:
             https://api.appcenter.ms/v0.1/apps/$APP_OWNER_NAME/$APP_NAME/releases)
 
           echo "Release response: $release_response"
+
+          release_id=$(echo $release_response | jq -r '.id')
+
+          echo "Release ID: $release_id"
+
+          if [ -z "$release_id" ]; then
+            echo "Error: release_id is empty"
+            exit 1
+          fi
+
+          echo "Release created successfully in App Center with ID: $release_id"
